Pins development
VCityTeam/UD-Demo-TIGA-Webdoc-ChemistryValley pull request #1
Opened 2021-12-08 10:35 UTC by CorentinGaut

Go a stable demo with pins object in the ud-vz scene : 
- Click on it to show details of the episode
- Add an episode class with specific CSS to build easily
- Compass

Next step : 
- Lock episode with a config file wich it will be specify to the progress of the user
- Search bar for episode 
- Tactile inputs

2021-12-08 15:45 UTC, EricBoix requested changes

2021-12-08 15:45 UTC, EricBoix commented on index.html
> +    </script>
Redundant script close

2021-12-08 15:45 UTC, EricBoix commented on src/EpisodeVisualizer.js
> +    //Create Pins
NIce comment ;-P

2021-12-08 15:45 UTC, EricBoix commented on src/Help.js
> +import { ModuleView } from '../node_modules/ud-viz/src/Widgets/Components/ModuleView/ModuleView';
Don't import with installation relative path but with something similar to
[`import { Widgets, Components } from 'ud-viz';`](https://github.com/VCityTeam/UD-Demo-DatAgora-Vegetalisation-PartDieu/blob/125e5b60e32efd111e729e40b1d3ad484f9e5c8b/ud-viz-context/BaseDemo.js#L4)

2021-12-08 15:45 UTC, EricBoix commented on src/bootstrap.js
> +  const positionPins_1 = new udviz.THREE.Vector3(1843554.77, 5165405.73, 220);
Avoid hardcoding data in code but use a config file.

2021-12-08 15:45 UTC, EricBoix commented on src/bootstrap.js
> +  episode_1.createPin(positionPins_1,"../assets/img/Episode1_1.png","../assets/img/Episode1_1_lock.png",false);
In the above mentioned config file associate the pin position and the file (as opposed to separating them)

2021-12-08 15:45 UTC, EricBoix commented on src/bootstrap.js
> +  compass.style.position ='absolute';
Place this in a css file.

2021-12-08 15:45 UTC, EricBoix commented on src/bootstrap.js
> +          //window.open("https://www.derrierelesfumees.com/_Contenusdlf/Episodes/Episodes01/index.html")
Remove this comment.

2021-12-08 15:45 UTC, EricBoix commented on src/bootstrap.js
> +    let mouse3D = new udviz.THREE.Vector3( ( event.clientX / window.innerWidth ) * 2 - 1,
Use pickObjectsAt as [done here](https://github.com/VCityTeam/UD-Viz/blob/master/src/Widgets/Components/LayerManager/LayerManager.js#L135)

2021-12-08 15:45 UTC, EricBoix commented on src/bootstrap.js
> +          intersects[ 0 ].object.material.color.set("rgb(200, 200, 200)");
Check the code of CityObjectProvider: on how they deal with color changes.

2021-12-08 15:45 UTC, EricBoix commented on src/bootstrap.js
> +/** @format */
Think of promoting this code to ud-viz.[...]Widgets.

2022-01-04 14:54 UTC, CorentinGaut commented on src/bootstrap.js
> +  episode_1.createPin(positionPins_1,"../assets/img/Episode1_1.png","../assets/img/Episode1_1_lock.png",false);
Done

2022-01-04 14:54 UTC, CorentinGaut commented on src/bootstrap.js
> +  compass.style.position ='absolute';
Done

2022-01-04 14:57 UTC, EricBoix commented on src/bootstrap.js
> +    let mouse3D = new udviz.THREE.Vector3( ( event.clientX / window.innerWidth ) * 2 - 1,
@CorentinGaut said: the created object does not seem to appear in the list of pickable object.

2022-01-04 14:58 UTC, EricBoix commented on src/bootstrap.js
> +          intersects[ 0 ].object.material.color.set("rgb(200, 200, 200)");
Same issue as above.

2022-01-04 15:02 UTC, EricBoix commented on src/bootstrap.js
> +    let mouse3D = new udviz.THREE.Vector3( ( event.clientX / window.innerWidth ) * 2 - 1,
Issue #4 opened.

2022-01-04 15:03 UTC, EricBoix approved these changes

2022-01-04 15:08 UTC, EricBoix commented on src/EpisodeVisualizer.js
> +   * @param {JSON} episodeConfig JSON data of your episode
Promote this JSON to a native JS object. The usage made of the episodeConfig json
string is only to create an EpisodeContent. Pass this EpisodeContent as argument to
this constructor instead ?

2022-01-04 15:13 UTC, EricBoix approved these changes

2022-01-05 13:31 UTC, EricBoix requested changes

2022-01-05 13:31 UTC, EricBoix commented on README.md
> +The template application can be locally (on your desktop) started in the following way
All what concerns the original ud-viz-template should be declined to this demo.

2022-01-18 14:12 UTC, EricBoix approved these changes
Some work deported to newly opened issues e.g. #6

2022-01-18 15:38 UTC, EricBoix commented on README.md
> +The template application can be locally (on your desktop) started in the following way
Place in issue #7

2022-01-18 15:38 UTC, merged